USE GoodEats;

#Timely 
SELECT LICENSENO, MAX(RESULTDTTM)
FROM GRADES
WHERE LICSTATUS = 'Active'
GROUP BY LICENSENO
;

SELECT MAX(RESULTDTTM)
FROM GRADES;


#Accurate
SELECT GRADES.LICENSENO, GRADES.RESULTDTTM, SUM_VIOLATIONS, SUM(VIOLLEVEL), DESCRIPT
FROM GRADES, VIOLATIONS
WHERE GRADES.LICENSENO = VIOLATIONS.LICENSENO
AND GRADES.RESULTDTTM = VIOLATIONS.RESULTDTTM
GROUP BY GRADES.LICENSENO, GRADES.RESULTDTTM, SUM_VIOLATIONS
ORDER BY GRADES.LICENSENO, GRADES.RESULTDTTM;


#Success and Performance
SELECT VIOLSTATUS, COUNT(LICENSENO), VIOLLEVEL
FROM VIOLATIONS
WHERE VIOLSTATUS LIKE '%Pass%' OR VIOLSTATUS LIKE '%Fail%'
GROUP BY VIOLSTATUS, VIOLLEVEL;

SELECT LICENSENO, RESULT, COUNT(LICENSENO)
FROM GRADES
GROUP BY LICENSENO, RESULT
ORDER BY LICENSENO ASC, RESULT DESC;

SELECT LICENSENO, RESULT, COUNT(LICENSENO), YEAR(RESULTDTTM)
FROM GRADES
GROUP BY LICENSENO, RESULT, YEAR(RESULTDTTM)
ORDER BY LICENSENO ASC, RESULT DESC;






