#Create Database and Tables

DROP Schema IF EXISTS GoodEats;

CREATE DATABASE IF NOT EXISTS GoodEats DEFAULT CHARACTER SET utf8;
USE GoodEats;

CREATE TABLE IF NOT EXISTS GRADES (
	LICENSENO		char(100)	NOT NULL,
	ISSDTTM			datetime	NULL,
	EXPDTTM			datetime	NULL,
	LICSTATUS		char(8)		NULL,
    LICENSECAT		char(10)	NULL,
    DESCRIPT		char(45)	NULL,
    RESULT			char(12) 	NULL,
    RESULTDTTM		datetime	NOT NULL,
    SUM_VIOLATIONS	int(4)		NULL,
    SCORE			int(3)		NULL,
    GRADE			char(1)		NULL,
    CONSTRAINT GRADES_PK PRIMARY KEY(LICENSENO, RESULTDTTM)
);

CREATE TABLE IF NOT EXISTS VIOLATIONS (
	LICENSENO		char(100)	NOT NULL,
    RESULTDTTM		datetime	NULL,
    VIOLATION		char(45)	NULL,
    VIOLLEVEL		char(10)	NULL,
    VIOLDESC		char(100)	NULL,
    VIOLDTTM		datetime	NULL,
    VIOLSTATUS		char(10)	NULL,
	CONSTRAINT VIOLATIONS_FK FOREIGN KEY(LICENSENO, RESULTDTTM)
    REFERENCES GRADES(LICENSENO, RESULTDTTM)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);


#Insert Data

LOAD DATA LOCAL INFILE '~/Desktop/DataChallenge/grades.csv'
INTO TABLE GRADES
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '~/Desktop/DataChallenge/violations.csv'
INTO TABLE VIOLATIONS
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


UPDATE VIOLATIONS
SET VIOLLEVEL = 10
WHERE VIOLLEVEL = '***';

UPDATE VIOLATIONS
SET VIOLLEVEL = 7
WHERE VIOLLEVEL = '**';

UPDATE VIOLATIONS
SET VIOLLEVEL = 2
WHERE VIOLLEVEL = '*';

